name: Test

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: go build -v ./... 
